arrowParens: "always"
bracketSpacing: false
embeddedLanguageFormatting: "auto"
endOfLine: "lf"
htmlWhitespaceSensitivity: "strict"
bracketSameLine: false
jsxSingleQuote: false
printWidth: 99
quoteProps: "as-needed"
semi: false
singleQuote: false
tabWidth: 4
trailingComma: "all"
useTabs: false

# JSDoc plugin
jsdocSpaces: 1
jsdocDescriptionWithDot: false
jsdocDescriptionTag: false
jsdocVerticalAlignment: false
jsdocKeepUnParseAbleExampleIndent: false
jsdocSingleLineComment: true
jsdocSeparateReturnsFromParam: false
tsdoc: true

plugins:
  - ./node_modules/prettier-plugin-jsdoc

overrides:
  - files:
      - "*.html"
      - "*.yml"
      - "*.yaml"
      - "*.json"
      - "*.css"
      - "*.scss"
      - "*.prisma"
    options:
      tabWidth: 2
